### PR TITLE
Update package.json for working with ESLint 5

### PR DESCRIPTION
**Pull request by Alex-Sokolov**
ESLint 5 released, changed peerDependencies to higher version

### CODE REVIEW

**Comment by edmorley** [comment]
Travis is failing:
https://travis-ci.org/webpack-contrib/eslint-loader/jobs/397734469#L593

**Comment by edmorley** [comment]
Ah - the Travis failures seen here are unrelated to the ESLint 5 upgrade, but are instead due to a change in webpack output between webpack `4.11.1` and `4.12.0`:
webpack/webpack#6542

...and this repository doesn't have a lockfile, so Travis is just pulling in latest (and there have been no landings on `master` since Feb, which is why it still looks green in Travis history).

The expected output just needs updating.

IMO this is a good example of why even libraries/consumable packages should still have lockfiles (and then use tools like https://renovatebot.com/ to automatically refresh them on a schedule).

**Comment by edmorley** [comment]
I've opened PR #235 to fix the unrelated test failures seen here.

**Comment by MoOx** [comment]
Can you rebase your pr on master so tests go green? thanks

**Comment by MoOx** [comment]
Also please update dev deps so we are sure it's ok.

**Comment by Alex-Sokolov** [comment]
@MoOx now ok?

**Comment by Alex-Sokolov** [comment]
Closed for https://github.com/webpack-contrib/eslint-loader/pull/240

**Pull request closed without merging**
