### PR TITLE
Fix corrupted filenames if cwd=="/"

### PR DESCRIPTION
**Pull request by nryabkov**
Otherwise it breaks build

### CODE REVIEW

**Comment by MoOx** [comment]
@nryabkov could you provide a test? thx

**Comment by MoOx** [comment]
There is also a conflict to fix, sorry

**Comment by ricardogobbosouza** [comment]
Hi @nryabkov 
I am helping to maintain this package.
Please, provide a test for this.

**Comment by imyzf** [comment]
Great! It fixed a problem when using eslint-loader in Electron. Because Electron's `process.cwd()` is `/`.

**Pull request closed without merging**
