### PR TITLE
docs: formatting

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Feel free to merge when CI will be green

**Comment by ricardogobbosouza** [comment]
@evilebottnawi I need you to approve to merge
`Merging can be performed automatically with 1 approving review.`

**Comment by ricardogobbosouza** [comment]
Bug on azure pipelines :disappointed:
Stopped on MacOS

**Comment by ricardogobbosouza** [comment]
@evilebottnawi 
I can't push to branch master
https://github.com/webpack-contrib/eslint-loader/pull/294#issuecomment-534702207

**Comment by evilebottnawi** [comment]
@ricardogobbosouza try again

**Comment by ricardogobbosouza** [comment]
@evilebottnawi 

remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "licence/cla" is expected. At least 1 approving review is required by reviewers with write access.
To github.com:webpack-contrib/eslint-loader.git
 * [new tag]         v3.0.1 -> v3.0.1
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:webpack-contrib/eslint-loader.git'

**Comment by evilebottnawi** [comment]
@ricardogobbosouza problem still exists?

**Comment by ricardogobbosouza** [comment]
@evilebottnawi  yes

**Comment by evilebottnawi** [comment]
@ricardogobbosouza what is email on commit? CLA failed when email is invalid for commit

**Comment by evilebottnawi** [comment]
@ricardogobbosouza try again

**Comment by ricardogobbosouza** [comment]
@evilebottnawi sorry, its works

**Comment by evilebottnawi** [comment]
Great! Feel free to ping me if you need help with something, you can invite other people as member if you need help from other developers (you have permission), anyway before big release will be great if somebody review your code (like me or other developers from webpack/webpack-contrib)

**Comment by ricardogobbosouza** [comment]
Ok, thanks

**Pull request merged**
