### PR TITLE
Use a more robust method to check for subdirectory membership.

### LINKED ISSUE #219: Relative resourcePath replacement is insufficently robust
When linting a file outside of the subtree of the current working directory, if the root of the file has a text match for the current working directory, eslint-loader will pass incorrect resourcePaths to eslint.

This occurred for me in this case, where the `cwd` is `kolibri` and files are being linted in a sibling folder `kolibri_exercise_perseus_plugin` - because of the naive match here:
```
  // remove cwd from resource path in case webpack has been started from project
  // root, to allow having relative paths in .eslintignore
  if (resourcePath.indexOf(cwd) === 0) {
    resourcePath = resourcePath.substr(cwd.length + 1)
  }
```
this returns invalid resourcePaths beginning with `_exercise_perseus_plugin`, which are not resolveable, because they don't exist.

### PR DESCRIPTION
**Pull request by rtibbles**
Fixes #219 by implementing a more robust subdirectory check. Adapted from https://stackoverflow.com/a/42355848

### CODE REVIEW

**Comment by rtibbles** [comment]
Anything I can do to get this merged? Currently having to run from a fork due to this issue being unresolved.

**Comment by MoOx** [comment]
A test would help to get this merged.

**Comment by ricardogobbosouza** [comment]
Hi @rtibbles 
I am helping to maintain this package.
Please provide a test for this.

**Comment by ricardogobbosouza** [comment]
No updating or testing

**Pull request closed without merging**
