### PR TITLE
Use getFormatter instead of path

### PR DESCRIPTION
**Pull request by rcoundon**
Upgraded to 6.0.1 of eslint and load formatter using either default eslint or user supplied eslint.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack-contrib/eslint-loader/pull/275?

**Comment by ricardogobbosouza** [comment]
Yes duplicate!
@evilebottnawi when will we have a new version released?
We need support for eslint 6 as fast as possible

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/eslint-loader/issues/277

**Comment by ricardogobbosouza** [comment]
@rcoundon
Closing for duplicate

**Pull request closed without merging**
