### PR TITLE
ci: test

### PR DESCRIPTION
**Pull request by evilebottnawi**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

test CI and update some deps

### Breaking Changes

No

### Additional Info

No

### CODE REVIEW

**Comment by evilebottnawi** [comment]
What the hell is going on with azure :confused:

**Comment by ricardogobbosouza** [comment]
@evilebottnawi I don't know, I honestly don't use azure

**Comment by evilebottnawi** [comment]
Degradation https://status.dev.azure.com/, let's wait

**Comment by evilebottnawi** [comment]
Strange, CI does hang :confused:

**Comment by ricardogobbosouza** [comment]
@evilebottnawi finally :grin:

**Comment by ricardogobbosouza** [comment]
@evilebottnawi Do not know if I understand, do you want a changelog file or what I describe?

**Comment by evilebottnawi** [comment]
@ricardogobbosouza i will generate changelog using `standard-release` and add additional lines which you provide here

**Comment by ricardogobbosouza** [comment]
## Bugfix
- Fix corrupted filenames if cwd == "/"
- Cannot use string formatter in outputReport
- No Output Report in File when build fails under webpack 4
- Add posibility to use absolute file path in outputReport.filePath
- It should be possible to use absolute file path in outputReport.filePath

## Features
- Validate schema options

## Breaking Changes
- Drop support for Node < 8.9.0
- Minimum supported webpack version is 4
- Minimum supported eslint version is 5

**Comment by evilebottnawi** [comment]
I will do release in near future

**Pull request merged**
